- src/pages/_app.js
> Fix title in the head

- package.json
**What kind of change does this PR introduce?**
npm script to build dev was missing
added script to package.json
> fix: add develop script into package.json

- .adviserrc.json
- dev.wh.config.json
- next.config.js
- package-lock.json
- package.json
- src/pages/_app.js
Add [Adviser](https://jam3.github.io/adviser/) web hint plugin to the generator
Link: [https://www.npmjs.com/package/adviser-plugin-webhint](https://www.npmjs.com/package/adviser-plugin-webhint)
Lack of local web tests
Integrate adviser web hint plugin to run webhint on the CI/CD.
> [Feature] Add adviser webhint plugin and fixes

- .ls-lint.yml
- package-lock.json
- package.json
feature: ls lint integration
- new package ls-lint
- executes as part of the 'npm run linters'
- created basic rules to support the generator's existing file naming conventions
> New Linter ls-lint

- .prettierrc
- scripts/templates/page/Page.js
- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.scss
- src/components/Footer/Footer.stories.js
- src/components/Layout/Layout.js
- src/components/Layout/Layout.module.scss
- src/components/Nav/Nav.js
- src/components/Nav/Nav.module.scss
- src/data/routes.js
- src/pages/_app.js
- src/pages/about/index.js
- src/pages/index.js
- src/styles/global.scss
- src/styles/vars.scss
- Create generic Footer component which holds list of all routes
- Move Nav and RotateScreen to Layout, have all top level components on the same level (Nav, Main, Footer)
- Use `<main>` tag for pages rather than section, add appropriate styles
- Add mobile/desktop height to Nav using vars
- Add simple routes file for page routes to be used within Nav and Footer
> Feature: Add Footer component and update HTML semantics

- .adviserrc.json
- lint-staged.config.js
NOTE
---
1. fix: .prettierignore and .eslintignore files were not being correctly used.
> fix: eslintignore and prettierignore not working

- .adviserrc.json
- next.config.js
> fix: output source map to develop and staging

- src/components/Layout/Layout.js
> fix: improve handleRouteChange method

- package-lock.json
- src/components/Unsupported/Unsupported.module.scss
- src/pages/about/index.js
- src/pages/index.js
> fix: replace uselayouteffect

- src/components/Image/Image.tsx
- src/utils/hooks/use-layout.ts
- src/utils/layout.ts
the surface problem reported was that the `sizes` prop had an incorrect type
however this PR would also fix another somewhat breakpoint related typing problem 😆
> fix: the `sizes` prop in Image.tsx

- .eslintrc.json
- package-lock.json
- package.json
- scripts/templates/page/Page.tsx
- src/components/Footer/Footer.tsx
- src/components/Head/Head.tsx
- src/components/Image/Image.tsx
- src/components/Layout/Layout.tsx
- src/components/Nav/Nav.tsx
- src/pages/404/index.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/about/index.tsx
- src/pages/index.tsx
- src/pages/unsupported/index.tsx
- src/utils/layout.ts
- tsconfig.json
https://nextjs.org/docs/advanced-features/module-path-aliases
> feature: Absolute Imports and Module path aliases

- .babelrc
- next.config.js
- package-lock.json
- package.json
> fix: svg loader issue

- .storybook/main.js
- .storybook/next-preset.js
- package-lock.json
- postcss.config.js
autoprefix works out of box, so removing the local postcss config
> fix: remove postcss autoprefix

- README.md
> fix: update cicd step

- .eslintrc.json
> fix: false positive for no-document-import-in-page

- .eslintrc.json
Reverts Jam3/nextjs-boilerplate#151
> Revert "fix: false positive for no-document-import-in-page"

- README.md
- codeship-services.yml
Codeship will fail pushing the Docker image to cache due to missing `.env` file.
The config in codeship-services.yml can only be enabled when needed.
> fix: ssh env

- src/components/Head/Head.tsx
> fix: set default twitter card

- .eslintignore
- .gitignore
- .prettierignore
- lint-staged.config.js
> fix: clean up linters and ignores

- .adviserrc.json
- .husky/commit-msg
- .husky/pre-commit
- .husky/pre-push
- Dockerfile
- package-lock.json
- package.json
Husky was outdated. More details here: https://blog.typicode.com/husky-git-hooks-javascript-config/
Upgrade it from version 4 to version 7
> Upgrade husky

- package-lock.json
- src/components/CookieBanner/CookieBanner.tsx
> fix: typescript error in cookie banner component

- src/components/Layout/Layout.tsx
- src/utils/analytics.tsx
> fix: google tag manager use next/script

- src/components/RotateScreen/RotateScreen.tsx
- src/services/orientation.ts
- src/services/pointer-move.ts
- src/services/raf.ts
- src/services/resize.ts
- src/services/scroll.ts
- src/services/visibility.ts
Sometimes we get into performance problems due to the number of event listeners present in a project. For instance, when we have several components in a list that listen to the resize event, or when we are developing a game and end up with several requestAnimationFrames scattered throughout the project, it becomes hard to manage and performance suffers.
Introducing services!
```
src/
services/
orientation.js
resize.js
visibility.js
...
```
This is very useful. If you ever worked with Angular this will be straightforward to you.  
A service is typically a class with a narrow, well-defined purpose. It …
> Introducing services!

- package-lock.json
- scripts/code-generator.js
> fix: template script

- .ls-lint.yml
- .storybook/main.js
- src/components/CookieBanner/CookieBanner.module.scss
- src/components/svgs/_.stories.tsx
> fix: minor chores

- src/services/cookie.ts
- src/services/local-storage.ts
- src/services/lock-body-scroll.ts
- src/services/orientation.ts
- src/services/pointer-move.ts
- src/services/raf.ts
- src/services/resize.ts
- src/services/scroll.ts
- src/services/visibility.ts
Services autocompletion/autoimport were not working well.
Creating a variable pointing to the service instance solved the intellisense issues.
- Fixed the resize service with the latest code used in a real project.
- Also added 2 new services for handling cookies and local-storage. By using them instead of directly interacting with the browser we are able to listen for changes and react to them.
> Improve services intellisense

- .eslintrc.json
- .storybook/intro/4.svg.stories.tsx
- scripts/server/index.js
- src/components/Head/Head.tsx
- src/components/Layout/Layout.tsx
- src/components/Nav/Nav.tsx
- src/hooks/use-cookie-banner.ts
- src/hooks/use-layout.ts
- src/pages/404/index.tsx
- src/pages/about/index.tsx
- src/pages/index.tsx
- src/services/cookie.ts
- src/services/local-storage.ts
- src/services/orientation.ts
- src/services/pointer-move.ts
- src/services/raf.ts
- src/services/resize.ts
- src/services/scroll.ts
- src/services/visibility.ts
- src/utils/analytics.tsx
- src/utils/basic-functions.ts
- inconsistence coding style of if/if-else block statement 
- use of `var`
- code readability and maintainability
- unused `containerRef`
- implement a new eslint rule , called `curly`
- implement a new eslint rule, called `no-vars`
- improve code readability and maintainability
- clean up code
> fix: improve amintainability and code readability and add eslint rules

- src/components/Layout/Layout.tsx
> fix: lazy load cookie banner

- .eslintrc.json
- package-lock.json
- package.json
> feature: new eslint plugin sonarjs

- .circleci/CircleCI.md
- .circleci/config.yml
- package-lock.json
- package.json
1. Refactor and reuse node container
2. Cache NextJS build and standardize the use of cache
> [Fix] [WIP] Improve CircleCI

- .circleci/config.yml
> [WIP] test slack fail message

- .circleci/CircleCI.md
Fixed misspelling at CircleCi.md an added extra steps
> Modified readme circleCI

- next.config.js
- package-lock.json
- package.json
> fix: update next config

- .circleci/scripts/deploy.sh
> fix: update deploy script

- .eslintrc.json
- package-lock.json
- package.json
- src/components/AppAdmin/AppAdmin.tsx
- src/components/Layout/Layout.tsx
- src/hooks/index.ts
- src/hooks/use-layout.ts
- src/hooks/use-window-size.ts
- types.d.ts
This is using the `useWindowSize` from #226 to avoid conflicts in the future @DonghyukJacobJang
> chore: remove react hooks library

- src/hooks/use-combined-refs.ts
- src/hooks/use-hash-state.ts
- src/hooks/use-intersection-observer.ts
- src/hooks/use-low-power-mode.ts
- src/hooks/use-orientation.ts
- src/hooks/use-reduced-motion.ts
- src/hooks/use-scroll-direction.ts
- src/hooks/use-window-size.ts
- src/hooks/use-window-visible.ts
- src/utils/detect-low-power-mode.ts
We often need a set of hooks on every project and end up copy/pasting them from previous projects.
I'm adding the most common ones I've been copying/pasting over the last year. I like to have these included on the boilerplate itself, instead of in "@jam3/react-hooks" because it allows us to make modifications based on the project requirements, which often becomes very complicated if the hooks are defined in a separate package.
> A bunch of hooks

- .ls-lint.yml
> Enhancement: add regex check to exclude filname with +

- package.json
- scripts/fix-lfs-hooks.ps1
- scripts/prepare.js
``npm run prepare`` currently breaks on windows machine that is running powershell. this is a work around to this solution
***Before***
***After***
> fix: lfs-hooks for windows powershell

- README.md
N/A
The current readme suggests using `true` as the value for "source.fixAll.eslint", which is deprecated. The value should be a string, of one of the following values:  `always`, `explicit`, `never`. Explicit will only run this eslint save action when a save is explicitly made. See https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save for more details.
Update readme to use the correct string value.
> fix: update eslint fixall setting in readme
