- .adviserrc.json
We need to remove LICENSE as a blacklisted file since builds are failing because adviser root-files rule 
The generator should keep the LICENSE MIT since it will be an open source project
When we clone or download the zip for client work we have to remove the LICENSE since is not MIT open source at that point
May be worthy to add this info in the Get Started
> Remove LICENSE file as blacklisted root-file

- next.config.js
Change
---
- Add `exportTrailingSlash: true` option in the next config
Current behavior
---
-  It generates `[page-name].html` when exporting static HTML
Expected behavior
---
- Exporting `/[page-name]/index.html`
> Export /page-name/index.html

- .adviserrc.json
Whitelisting `[1217]` until there is a fix https://www.npmjs.com/advisories/1217
> Whitelist 1217 vulnerability issue

- public/robots.txt
- scripts/robots-txt-generator.js
Refine robots.txt, and make sure the full indexable version is used only on production environments.
Make sure that in your **production CI pipeline**, you specify the environment variable `CI_ENV=production`
> fix: robots.txt per environment

- .adviserrc.json
- lint-staged.config.js
- package.json
An issue is occurred when working with dynamic page/routing. lint-staged fails due to the file name that is wrapped brackets. 
Opened issue: https://github.com/okonet/lint-staged/issues/676
Reference: https://github.com/zeit/next.js/blob/canary/lint-staged.config.js
> fix: lint-staged issue when having dynamic pages

- package.json
Fix for: https://github.com/Jam3/nyg-nextjs/issues/23
~~- [ ] I lightly tested it in one browser~~
~~- [ ] I deeply tested it in several browsers~~
~~- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)~~
Issue applies only to pre-commit scripts, I tested it on my Windows machine, and on my Macbook to ensure the glob pattern works for both
Linter script glob pattern doesn't work on Windows
Double-quoted the glob pattern
Found the solution here: https://stackoverflow.com/questions/51021751/express-js-lint-gives-mistake
> [#23] [Fix] Linter script glob pattern Windows support

- next.config.js
- package.json
NOTE: 
- `optimize-css-assets-webpack-plugin` is no longer required. NextJS is now supporting this by default for a production build.
> fix: remove webpack css minify config

- src/components/Nav/Nav.js
Removing console error caused by Link having a functional component as a child.
https://github.com/vercel/next.js/issues/7915
> Fix: Link Functional Component Forward Ref

- next.config.js
- src/styles/export-vars.module.scss
- src/styles/global.scss
- src/utils/layout.js
Currently when we want to access a Sass variable within JavaScript, we add it to a CSS variable and retrieve using `getPropertyValue('--var')`. Now that we're SSR'ing, we are only able to access these variables on the browser side. Due to this limitation, this feature adds the ability to import sass variables directly in our JavaScript files that works on server side.
Caveats: 
1) Requires overwriting a cssLoader option. (https://github.com/vercel/next.js/issues/11629)
2) Scss export file is required to be a `.module.scss` otherwise NextJS will throw error (https://github.com/vercel/next.js/blob/master/errors/css-global.md).
> Feature: Access Sass Variables within Javascript

- scripts/templates/page/Page.js
- src/components/Head/Head.js
- src/components/Head/Head.stories.js
- src/data/settings.js
- src/pages/_app.js
- src/pages/about/index.js
- src/pages/index.js
- src/utils/hooks/use-layout.js
- Move Head from _app to its own component and contain all Head logic within.
- Easier/Cleaner to specify props from page level such as title, description, keywords etc.
- Add title logic in the format of `Jam3 Generator | The Relentless Pursuit of Better` for home page and `About | Jam3 Generator` for other pages.
> Feature: Make Head separate component

- package.json
Currently it's not possible to access files in `public` folder while using storybook. This PR enables that functionality.
https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook
> Serve Static Files Via Storybook

- .ls-lint.yml
fix: allowing dynamic route files to pass ls lint check
> ls-lint Allow Dynamic Route Files

- public/favicons/html_code.html
- src/components/Head/Head.js
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
site.webmanifest returning 401 when behind Basic Auth
Add crossorigin use-credential even if under same origin as per [MSDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#example_webmanifest_with_credentials)
> Fix: Add crossorigin for webmanifest

- next.config.js
Fix Image compression with next 11 and webpack 5
Reference: https://github.com/cyrilwanner/next-optimized-images/issues/251
> fix: image compression w/ next 11

- .eslintrc.json
- package.json
Next 11 released an eslint package with next specific warnings
Reference: https://nextjs.org/docs/basic-features/eslint
Some warnings like images are not useful to us because we don't use Vercel but still should be nice to have
> feature: add eslint next package

- .babelrc
- next.config.js
- package-lock.json
- package.json
> fix: [issue-71] disable svgo minify id attr

- next.config.js
- package-lock.json
NextJS 10+ now support CSS/SCSS as well as CSS and SCSS `modules` by default.
https://nextjs.org/docs/basic-features/built-in-css-support#sass-support
removing the custom webpack config.
No side effects at all. The app will run as before.
> fix: remove custom scss module webpack config

- .github/PULL_REQUEST_TEMPLATE.md
Github PRs are not integrated with Jira
1. Add the Jira ticket id in the Pull Request Template
If Jira is integrated with Github, adding the Jira Ticket ID it's going to link a specific ticket with the commits.
To learn more check: https://support.atlassian.com/jira-software-cloud/docs/process-issues-with-smart-commits/
> Add Jira support in every PR

- .codeship/artifact.sh
- .codeship/set-lfs.sh
- README.md
- codeship-services.yml
- decrypt-env.sh
- encrypt-env.sh
Codeship Pro for his docker based nature doesn't support natively Git LFS. 
We cloned the Codeship [git lfs script](https://github.com/codeship/scripts/blob/master/packages/git-lfs.sh), and re-factored it to work on a docker container. As well of integrate the mechanism to use a private key that will let Git LFS to download the files from the repository as Git doesn't have access to the repository once docker runs.
The solution is not enabled by default and the steps are in the Readme
> feature: integrate git lfs for codeship pro projects

- src/data/routes.ts
- src/pages/index.module.scss
- src/pages/index.tsx
- src/types/index.ts
I have been wanting to do this for a while 😂 
the main reason being: "Landing" should be the page users land on, although sometimes it's likely to be the root page; on the other hand, "Home" normally means the root page, which I think is more concise...
let me know what you think 😂 
also, on an unrelated note, I think "JAMstack" is now called "Jamstack" (different casing), maybe we want to change it in the repo description on the right
> chore: rename Landing to Home

- Dockerfile
We used this fix in a couple of projects to fix Codeship build breaking
`node:14` docker image as its build environment which has node version 14.17.6.
That image is built on an OS (debian stretch) that comes with `zlib1g 1.2.8`, which does not satisfy building the `mozjpeg` dependency based on required `zlib1g 1.2.9+`. See https://packages.debian.org/bullseye/zlib1g
Build a result build breaks:
Use another node image - `node:14-bullseye` that comes with comes with `zlib 1.2.11`
> feature: update Docker's node build

- src/components/Nav/Nav.tsx
- src/pages/about/index.tsx
- src/pages/index.tsx
- src/utils/gsap-init.ts
Proposal:
- Add a bit of motion as default on our pages, so for example coops have an idea of how we do motion from the beginning (but I could see how this might be too much and is better to keep the generator clean)
- Then probably the most spicy `registerEffect` I think we as a company we should start to use this https://greensock.com/docs/v3/GSAP/gsap.registerEffect() since we repeat ourselves  sometimes a lot in projects when it comes to animation (including me), things like fade from the bottom animations usually in motion bibles are all the same, and registerEffect allows for variations anyway
The not repeating ourselves, is inspired by the Singular Genomics motion bible which had like only 2-3 types of animation repeated everywhere 😆 but I still added `.from autoalpha: 0, y: 50` …
> feature: register effect gsap

- .storybook/main-theme.js
- .storybook/main.js
- .stylelintrc
- commitlint.config.js
- package.json
- src/components/Head/Head.tsx
- src/data/settings.ts
- src/styles/mixins.scss
- src/styles/shared.scss
By commits:
* [chore: add a welcome story](https://github.com/Jam3/nextjs-boilerplate/commit/e10bdaa0b69ad335b3689e5ff6de89fd4ca39299) - Add a default initial story for when localhost:9001 opens up
* [chore: add brandImage to storybook theme](https://github.com/Jam3/nextjs-boilerplate/commit/563aac792e05e085247747d404f292614d8c55d7) - getting that TODO done this just adds our logo at the top of the page sidebar
* [chore: add pxpush and motion to commitlint](https://github.com/Jam3/nextjs-boilerplate/commit/64ef303ee158da518790b2cc8ebb23258effc3ad) - adding two extra keywords to commitllint that I have used a lot in projects
* [chore: add siteDescription and siteKeywords under settings](https://github.com/Jam3/nextjs-boilerplate/commit/4a9bb5873424dd5a0589f1d57b8de89443f914c0) - add …
> chore: small fixes 

- .stylelintrc
- package-lock.json
- package.json
- src/components/CookieBanner/CookieBanner.module.scss
- src/components/Head/Head.tsx
- src/components/Nav/Nav.module.scss
- src/styles/global.scss
- src/styles/layout.scss
- src/styles/mixins.scss
* Moved the breakpoints to a single file `layout.scss`
* Added an `@error` in case you enter values that are not in `$layout` for example:
```scss
@include breakpoint(television) {} // this will throw an error now
```
* Create helper mixins for breakpoints to get autocomplete from stylelint and is less prone to errors than actually writing the values in $layout
Using:
```scss
// OLD WAY - but you can still use it if your prefer
@include breakpoint(tablet) {}
// NEW WAY
@include media-tablet {}
```
---
If you want to play around with this change
Here is a sass playground https://www.sassmeister.com/gist/7db97d8c46dbec83dee2368e3fa71353
> feature: mixins for breakpoints

- src/utils/gsap-effects.d.ts
- src/utils/gsap-init.ts
- tsconfig.json
This will help most significantly in applying effects to provide type checking as well as auto-complete. It will also help with registering the effects on defining required/optional config. The con being ppl adding an effect would need to go to two different files to achieve that...
> feature: improve gsap.registerEffect to be more TypeScript friendly

- next.config.js
From time to time, developers forget to remove debugging code such as `console.log`, `console.warn`, and more. 
At the build process, NextJS will suppress all `console` so that it makes more production ready. 
> fix: suppress console in production build

- src/data/settings.ts
- src/pages/_document.tsx
- src/styles/global.scss
- src/utils/set-body-classes.ts
Optional fix for static content flash -  FE won't show pre-rendered HTML until the app kicks in.
This is sort of decreases performance (1st meaningful pain) but makes sure motion works seamlessly on site load.
We can also set default to `false` if we like
This won't impact statically pre-rendered HTML and will display content with disabled JS as expected.
> Optional static HTML flash removal UP FOR DISCUSSION

- .storybook/preview.js
- .storybook/webpack.js
* **update Preview:**  decorators and parameters to match Nextjs app setup
* **update Webpack:** We can make it simple and eliminate the SVG path and only care about the extension.
This will allow injecting SVG as code from any folder and not stick to `components/svgs` this can be handy esp when bringing things from React UI library where icons can be contained within a component folder e.g VideoPlayer 
This is how our next webpack config is set up as well without specifying `components/svgs` path and simply looking at the SVG extension
> Storybook update

- src/utils/runtime-env.ts
- add support to return dev environment in `getRuntimeEnv()` method
> fix getRuntimeEnv() return environment

- .circleci/commands/main.yml
We noticed that the cache created by the package-lock.json was never being used as the `npm set-script` commands alter the pacakge.json and the package-lock.json creating a different checksum. Adding the `--no-save` flag ensures it does not create a new package-lock.json
> fix: add no-save to npm install
